import os
import sys
import unittest
import numpy as np
import scipy.io.wavfile as wav

# Ensure python runtime can resolve paths relative to project root
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from src.dsp_engine import analyze_satellite_signal, get_project_root


class TestDigitalSignalProcessingEngine(unittest.TestCase):

    def setUp(self):
        """
        Runs automatically before each test. Generates a pristine synthetic
        binary .wav signal containing a perfect 2400Hz pure tone carrier.
        """
        self.root_path = get_project_root()
        self.test_filename = "synthetic_test_signal.wav"
        self.target_path = os.path.join(self.root_path, "data", "raw", self.test_filename)

        # Signal Generation Parameters
        self.sample_rate = 11025
        duration = 4.0  # 4 seconds generates exactly 2 telemetry frames
        t = np.linspace(0, duration, int(self.sample_rate * duration), endpoint=False)

        # Create a pure 2400Hz wave vector (Simulating active satellite lock)
        carrier_frequency = 2400
        signal_vector = 0.5 * np.sin(2 * np.pi * carrier_frequency * t)

        # Inject minor background Gaussian noise matrix
        noise = np.random.normal(0, 0.05, len(signal_vector))
        final_signal = signal_vector + noise

        # Scale array values to standard 16-bit Signed Integer PCM constraints
        audio_data = (final_signal * 32767).astype(np.int16)

        # Write to raw directory registry
        os.makedirs(os.path.dirname(self.target_path), exist_ok=True)
        wav.write(self.target_path, self.sample_rate, audio_data)

    def tearDown(self):
        """
        Runs automatically after tests finish. Clears temporary testing data
        assets from disk arrays to keep environment space pristine.
        """
        if os.path.exists(self.target_path):
            os.remove(self.target_path)

        # Also clean up the processed data file side effect generated by the run
        processed_path = os.path.join(self.root_path, "data", "processed", "synthetic_test_signal_spectrogram.npy")
        if os.path.exists(processed_path):
            os.remove(processed_path)

    def test_dsp_mathematical_extraction(self):
        """
        Verifies if the DSP algorithm can successfully isolate the 2400Hz
        carrier, achieve lock status, and parse valid DataFrames.
        """
        df_output = analyze_satellite_signal(filename=self.test_filename)

        # 1. Structural Checks: DataFrame must exist and contain parsed values
        self.assertIsNotNone(df_output)
        self.assertFalse(df_output.empty)

        # 2. Frame Logic Validation: 4-second file / 2-second windows = 2 records
        self.assertEqual(len(df_output), 2)

        # 3. Mathematical Verification: Synthetic 2400Hz must yield carrier_lock = True
        first_frame_lock = df_output.iloc[0]["carrier_lock"]
        self.assertTrue(bool(first_frame_lock), "DSP engine failed to detect pure 2400Hz satellite subcarrier.")

        # 4. Range Assertions: SNR values must fall into valid positive numeric registers
        first_frame_snr = df_output.iloc[0]["snr_db"]
        self.assertGreater(first_frame_snr, 12.0, "SNR calculation falls below threshold tolerances.")


if __name__ == "__main__":
    unittest.main()
